### ISSUE TITLE
New Whitelist FIle type support

### ISSUE THREAD

**Issue by MrSnowGlobe** [cnaude/Whitelist#1]
Support for the new whitelist file type: .json?

Please and thankyou

**Comment by cnaude** [comment]
I am curious about this. How and why do you use this plugin? The latest CraftBukkit has a good whitelist command and supports json. Do you want the whitelist to be updated each time someone updates whitelist.json outside of the game?

**Comment by MrSnowGlobe** [comment]
Users white list on our website with some PHP script then their names get added to the servers white list automatically.

So this plugin fits the bill 100%

-----Original Message-----

**Comment by cnaude** [comment]
Latest dev version now supports json format. http://h.cnaude.org:8081/job/Whitelist/

**Comment by cnaude** [comment]
You will need to set "UUIDMode: true" in the config.yml. If you have existing txt file it will auto convert to json.
