### ISSUE TITLE
Kicking player after nobody login for long time

### ISSUE THREAD

**Issue by plachta11b** [cnaude/Whitelist#2]
Hi, can you fix this issue?

mSQL Error: The last packet successfully received from the server was 55,057,796 milliseconds ago.  The last packet sent successfully to the server was 55,057,796 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

You maybe should test connection before usage.

Why is sql lib file used for connections?

**Comment by cnaude** [comment]
Have you tried appending this to your connection string? is it kicking players that are already logged in? What version of database are you running?

`?autoReconnect=true`

**Comment by plachta11b** [comment]
> Have you tried appending this to your connection string?

I was scared by this: "The use of this feature is not recommended, because it has side effects related to session state and data consistency when applications don't handle SQLExceptions properly, and is only designed to be used when you are unable to configure your application to handle SQLExceptions resulting from dead and stale connections properly." source: http://pages.citebite.com/p4x3a0r8pmhm
Should i do this: SqlDriverConnection: jdbc:mysql://localhost/whitelist?autoReconnect=true ???

>  is it kicking players that are already logged in?

No. It only kick first player who login after many hours of inactivity. My server is often empty and nobody login. Second login always succeeds.

> What version of database are you running?

Ver 14.14 Distrib 5.5.50
5.5.50-0ubuntu0.14.04.1

> CONFIG

Enabled: true
FileCheckInterval: 1000 (not used)
KickMessage: Sorry %NAME%! you are not on the whitelist!
SqlEnable: true
SqlDriver: com.mysql.jdbc.Driver
SqlDriverConnection: jdbc:mysql://localhost/whitelist
SqlDriverJar: lib/mysql-connector-java-bin.jar (This file maybe not exist)
UUIDMode: false
DebugMode: false

**It only happen after long server emptyness when sql connection die because of inactivity**

**Comment by cnaude** [comment]
Please try this version: https://h.cnaude.org/jenkins/job/Whitelist/32/
I added some logic in there to reconnect when the connection has been closed.

**Comment by plachta11b** [comment]
Works great! Thanks a lot for fast fix :)
