### ISSUE TITLE
Problem with editing with a text editor.

### ISSUE THREAD

**Issue by UkropXD** [cnaude/Whitelist#6]
The problem is that when I try to edit the whitelist using a text editor, the changes are not applied and the player is not added to the whitelist, and after restarting the server, all changes related to the whitelist.txt are simply canceled.

**Comment by cnaude** [comment]
What version of Minecraft are you experiencing this issue on? What OS is the server running on?

**Comment by cnaude** [comment]
After some testing I've identified the problem. I'll have a new version uploaded soon.

**Comment by cnaude** [comment]
Go ahead and give this a try https://jenkins.chrisnaude.com/jenkins/job/Whitelist/41/artifact/target/Whitelist-3.5-41.jar
I recommend dropping the check interval down to 100 as well.

**Comment by UkropXD** [comment]
Thank you very much for such a quick response and resolving the issue, now everything works as it should! You're the best!
